# Generated by Django 4.2.3 on 2023-09-15 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_message_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='get_updates',
        ),
    ]
