# Generated by Django 4.2.3 on 2023-07-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_room_options_room_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
