# Generated by Django 4.2.3 on 2023-07-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_message_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_message',
            field=models.ManyToManyField(blank=True, related_name='liked_message', to='base.message'),
        ),
    ]
