# Generated by Django 4.2.3 on 2023-09-23 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_user_status_user_status_del_at_alter_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status_del_at',
        ),
    ]
