# Generated by Django 4.2.3 on 2023-07-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_room_is_private'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='limited_for',
            field=models.ManyToManyField(related_name='limited_for', to='base.class'),
        ),
    ]
