# Generated by Django 4.2.3 on 2023-09-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_fromclass_set_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='from_class',
        ),
        migrations.AddField(
            model_name='user',
            name='from_class',
            field=models.ManyToManyField(related_name='from_class', to='base.fromclass'),
        ),
    ]
