# Generated by Django 4.2.3 on 2023-07-15 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='from_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.class', to_field='name'),
        ),
    ]
