# Generated by Django 4.2.3 on 2023-10-03 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_userclass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserClass',
        ),
    ]
