# Generated by Django 4.2.3 on 2023-07-16 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_user_from_class'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='FromClass',
        ),
    ]
