# Generated by Django 4.2.3 on 2023-08-23 07:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_room_is_private_remove_room_limited_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='likes',
            field=models.ManyToManyField(related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
