# Generated by Django 4.2.3 on 2023-08-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_message_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
