# Generated by Django 4.2.3 on 2023-08-25 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_user_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='FromClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_class', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='limited',
            field=models.ManyToManyField(related_name='from_class', to='base.fromclass'),
        ),
        migrations.AddField(
            model_name='user',
            name='from_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.fromclass'),
        ),
    ]
