# Generated by Django 4.2.3 on 2023-10-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='user',
            name='school_year',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
