# Generated by Django 4.2.3 on 2023-08-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_fromclass_room_limited_user_from_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='limited',
        ),
        migrations.AddField(
            model_name='room',
            name='limited_for',
            field=models.ManyToManyField(to='base.fromclass'),
        ),
    ]
