# Generated by Django 4.2.3 on 2023-12-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_emailpasswordverification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fromclass',
            options={'verbose_name': 'Trieda', 'verbose_name_plural': 'Triedy'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created'], 'verbose_name': 'Správa diskusie', 'verbose_name_plural': 'Správy diskusií'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-pinned', '-updated', '-created'], 'verbose_name': 'Diskusia', 'verbose_name_plural': 'Diskusie'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Téma diskusie', 'verbose_name_plural': 'Témy diskusií'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Užívateľ', 'verbose_name_plural': 'Užívatelia'},
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(db_column='Meno', max_length=220, null=True),
        ),
    ]
