# Generated by Django 4.2.3 on 2023-08-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_remove_room_limited_room_limited_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fromclass',
            name='set_class',
            field=models.CharField(choices=[(22, 'IV.C'), (13, 'II.SC'), (3, 'I.C'), (23, 'IV.SA'), (15, 'III.B'), (25, 'IV.F'), (9, 'II.B'), (12, 'II.SB'), (21, 'IV.B'), (16, 'III.C'), (7, 'II.A'), (5, 'I.SB'), (2, 'I.B'), (19, 'III.SC'), (10, 'II.C'), (6, 'I.SC'), (11, 'II.SA'), (1, 'I.A'), (4, 'I.SA'), (17, 'III.SA'), (24, 'IV.SB'), (20, 'IV.A'), (14, 'III.A'), (18, 'III.SB')], max_length=5),
        ),
    ]
