# Generated by Django 4.2.3 on 2023-12-26 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_reportlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportLog',
        ),
    ]
