# Generated by Django 4.2.3 on 2023-08-26 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_room_limited_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_body', models.TextField()),
                ('reply_updated', models.DateTimeField(auto_now=True)),
                ('reply_created', models.DateTimeField(auto_now_add=True)),
                ('original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.message')),
                ('reply_likes', models.ManyToManyField(related_name='reply_messages', to=settings.AUTH_USER_MODEL)),
                ('reply_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.room')),
                ('reply_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reply_updated', '-reply_created'],
            },
        ),
    ]
