# Generated by Django 4.2.3 on 2023-08-26 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
