# Generated by Django 4.2.3 on 2024-01-12 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_room_subscribing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='subscribing',
        ),
    ]
