# Generated by Django 4.2.3 on 2024-02-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_remove_room_subscribing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fromclass',
            options={'verbose_name': 'Triedu/skupinu', 'verbose_name_plural': 'Triedy a skupiny'},
        ),
        migrations.AddField(
            model_name='room',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='room_image'),
        ),
    ]
