# Generated by Django 4.2.3 on 2023-08-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_delete_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='replies',
            field=models.ManyToManyField(related_name='message_replies', to='base.message'),
        ),
    ]
