# Generated by Django 4.2.3 on 2023-08-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_message_replies'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='replying',
            field=models.BooleanField(default=False),
        ),
    ]
