# Generated by Django 4.2.3 on 2024-02-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_fromclass_options_room_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='file',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to='', verbose_name='room_image'),
        ),
    ]
