# Generated by Django 4.2.3 on 2023-08-28 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_message_replying'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='replying',
        ),
    ]
