# Generated by Django 4.2.3 on 2024-02-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_alter_room_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registered_groups',
            field=models.BigIntegerField(default=0),
        ),
    ]
