# Generated by Django 4.2.3 on 2023-08-28 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_message_replying'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='replies',
        ),
        migrations.RemoveField(
            model_name='message',
            name='replying',
        ),
    ]
