# Generated by Django 4.2.3 on 2024-02-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_user_registered_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribing',
            field=models.ManyToManyField(related_name='subscribing_rooms', to='base.room'),
        ),
    ]
