# Generated by Django 4.2.3 on 2024-02-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_user_subscribing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscribing',
        ),
        migrations.AddField(
            model_name='room',
            name='subscribing',
            field=models.ManyToManyField(related_name='subscribing_rooms', to='base.room'),
        ),
    ]
