# Generated by Django 4.2.3 on 2024-02-19 15:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_remove_user_subscribing_room_subscribing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='subscribing',
            field=models.ManyToManyField(related_name='subscribing_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
