# Generated by Django 4.2.3 on 2024-02-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_alter_room_subscribing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='registered_groups',
        ),
        migrations.AddField(
            model_name='user',
            name='registered_groups',
            field=models.ManyToManyField(related_name='registered_groups', to='base.fromclass'),
        ),
    ]
