# Generated by Django 4.2.3 on 2024-02-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_remove_user_registered_groups_user_registered_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='fromclass',
            name='custom',
            field=models.BooleanField(default=False),
        ),
    ]
