# Generated by Django 4.2.3 on 2024-02-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_fromclass_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
