# Generated by Django 4.2.3 on 2024-02-26 08:53

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_remove_room_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[base.models.validate_image], verbose_name='avatar'),
        ),
    ]
