# Generated by Django 4.2.3 on 2024-02-28 10:24

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='file',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to='files/', validators=[base.models.validate_image], verbose_name='room_image'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(db_column='Meno', max_length=50, null=True),
        ),
    ]
