# Generated by Django 4.2.3 on 2024-03-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_alter_room_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-pinned', '-public', '-updated', '-created'], 'verbose_name': 'Diskusia', 'verbose_name_plural': 'Diskusie'},
        ),
        migrations.AddField(
            model_name='room',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
