# Generated by Django 4.2.3 on 2024-03-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_alter_room_options_room_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailpasswordverification',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
