# Generated by Django 4.2.3 on 2024-04-15 10:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_emailpasswordverification_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(db_column='Meno', max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(4, 'Tvoje meno je prikrátke')]),
        ),
    ]
