# Generated by Django 4.2.3 on 2024-05-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
