# Generated by Django 4.2.3 on 2024-05-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_alter_room_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='limited_for',
            field=models.ManyToManyField(null=True, related_name='room_limited_for', to='base.fromclass'),
        ),
    ]
